spring:
  application:
    name: umaservices-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/uma?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: root
    password: UMa@mysql2019
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 9090
management:
  port: 9091
dubbo:
  registry:
    id: umaservices-provider-registry
    address: nacos://127.0.0.1:8848
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  application:
    id: umaservices-provider
    name: umaservices-provider
  scan:
    basePackages: com.lgmn.umaservices.provider.service
demo:
  service:
    version: 1.0.0
nacos:
  config:
    server-addr: 127.0.0.1:8848
